### ISSUE TITLE
How to add Search Bar

### ISSUE THREAD

**Issue by Ajay-Dhangar** [Ajay-Dhangar/CodeMastermindHQ#3]
- [x]  How to add Search Bar

**Comment by Ajay-Dhangar** [comment]
**Tasks:**

- [ ] How to add Search Bar

Codes For Search Bar [click here](https://github.com/Ajay-Dhangar/CodeMastermindHQ/tree/main/src/theme/SearchBar)

**Comment by Ajay-Dhangar** [comment]
- [ ] Code is fully working and Search result very easily find out without any error / issues.
